site_name: VMX Computer Vision Docs
site_description: VMX Computer Vision Docs by vision.ai, LLC
theme_dir: custom_theme
site_favicon: img/favicon.ico
use_directory_urls: false

pages:
- ['index.md', 'Introduction']
- ['VMXAppBuilder.md', 'Learn VMX']
- ['api.md', 'VMX API']
- ['install.md', 'Installation']

copyright: <i></i>&copy; <a href="http://vision.ai">vision.ai</a> Docs9