site_name: VMX Docs
site_description: VMX Documentation by vision.ai, LLC
theme: cerulean
site_favicon: favicon.ico
use_directory_urls: False
pages:
- ['index.md', 'Introduction']
- ['VMXAppBuilder.md', 'AppBuilder']
- ['VMXmiddle.md', 'VMXMiddle']
- ['VMXserver.md', 'VMXServer']
